---
- name: Audit
  user: ansibledevops
  hosts: node1
  become: yes

  vars:
    - destination: /home/ec2-user/ansible-demo/audit/baseline.txt
  tasks:

    - name: Create a file
      file:
        dest: "{{ destination }}"
        state: touch
      delegate_to: localhost

    - name: Hostname
      shell:
        hostname
      register: hostname
    - debug:
        msg: "{{hostname.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== HOSTNAME =========="
        insertafter: OEF
      delegate_to: localhost


    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{hostname.stdout}}"
        insertafter: OEF
      delegate_to: localhost


    - name: Current date and time
      shell:
        date
      register: date
    - debug:
        msg: "{{date.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== DATE =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{date.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Operating System Information
      shell:
        cat /etc/os-release
      register: os_info
    - debug:
        msg: "{{os_info.stdout_lines}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== OPERATING SYSTEM =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{os_info.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: System Uptime
      shell:
        uptime
      register: uptime
    - debug:
        msg: "{{uptime.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== SYSTEM UPTIME =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{uptime.stdout}}"
        insertafter: OEF
      delegate_to: localhost
        
    - name: CPU Model
      shell:
        cat /proc/cpuinfo | grep name | cut -d':' -f2
      register: cpumodel
    - debug:
        msg: "{{cpumodel.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== CPU MODEL =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{cpumodel.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: CPU Speed
      shell:
        cat /proc/cpuinfo | grep MHz | cut -d':' -f2
      register: cpuspeed
    - debug:
        msg: "{{cpuspeed.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== CPU SPEED =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{cpuspeed.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: CPU Cores
      shell:
        cat /proc/cpuinfo | grep cores | cut -d':' -f2
      register: cpucores
    - debug:
        msg: "{{cpucores.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== CPU CORES  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{cpucores.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Total Physicall Memory
      shell:
        free -m | grep Mem | tr -s ' ' | cut -d ' ' -f2
      register: totalmemory
    - debug:
        msg: "{{totalmemory.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== TOTAL PHYSICAL MEMORY =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{totalmemory.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Used Physicall Memory
      shell:
        free -m | grep Mem | tr -s ' ' | cut -d ' ' -f3
      register: usedmemory
    - debug:
        msg: "{{usedmemory.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== USED PHYSICAL MEMORY =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{usedmemory.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: List of users created after Linux installation
      shell:
        " awk -F: '($3>999 && $3<65534) {print $1}' /etc/passwd "
      register: userslist
    - debug:
        msg: "{{userslist.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== LIST OF USERS CREATED AFTER LINUS INSTALLATION =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{userslist.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: List of users with Sudo access
      shell:
        " sudo grep '^sudo:.*$' /etc/group | cut -d: -f4 "
      register: usersWithSudoAccess
    - debug:
        msg: "{{usersWithSudoAccess.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== LIST OF USERS WITH SUDO ACCESS =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{usersWithSudoAccess.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Groups information
      shell:
        " awk -F: '($3>999 && $3<65534) {print $1 $3 $4}' /etc/group "
      register: GroupsInformation
    - debug:
        msg: "{{GroupsInformation.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== GROUPS INFORMATION =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{GroupsInformation.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Groups in Sudoers
      shell:
        " sudo cat /etc/sudoers | awk '{print $1}' | grep % "
      register: GroupsInSudoers
    - debug:
        msg: "{{GroupsInSudoers.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== GROUPS IN SUDOERS =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{GroupsInSudoers.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Information on the installed physical disks on a system
      shell:
        " sudo fdisk -l | head -2 | grep Disk "
      register: installedPhysicalDisks
    - debug:
        msg: "{{installedPhysicalDisks.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== HARD DISK INFORMATION  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{installedPhysicalDisks.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Information on the installed physical partitions on a system
      shell:
        sudo fdisk -l | tail -8 | awk '/dev/ { print $1 " " $5 " " $7 }'
      register: installedPhysicalPartitions
    - debug:
        msg: "{{installedPhysicalPartitions.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== HARD DISK PARTITION'S INFORMATION  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{installedPhysicalPartitions.stdout}}"
        insertafter: OEF
      delegate_to: localhost
        
    - name: Information on the available free disk space on a system
      shell:
        sudo df -h | awk '{if ($1 != "Filesystem" && $1 != "none") print $1 " " $5}'
      register: availableFreeDiskSpace
    - debug:
        msg: "{{availableFreeDiskSpace.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== HARD DISK INFORMATION (Free disk space)  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{availableFreeDiskSpace.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: IP Addresses
      shell:
        " ifconfig | grep broadcast | tr -s ' ' | cut -d' ' -f3 "
      register: IPAddresses
    - debug:
        msg: "{{IPAddresses.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== NETWORK DEVICES & IP ADDRESSES  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{IPAddresses.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: IP Routing Table
      shell:
        route
      register: IPRoutingTable
    - debug:
        msg: "{{IPRoutingTable.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== ROUTING TABLE  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{IPRoutingTable.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Install Nmap
      yum:
        name:
          - nmap
        state: latest

    - name: Scanning Open Ports
      shell:
        nmap -sT -p- 127.0.0.1 | sed 1,4d
      register: ScanningOpenPorts
    - debug:
        msg: "{{ScanningOpenPorts.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== OPEN PORTS  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{ScanningOpenPorts.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Audit Established SSH connections
      shell:
        sudo lsof -i -n -P | grep sshd | grep IPv4 | grep ESTABLISHED
      register: AuditSSHConnections
    - debug:
        msg: "{{AuditSSHConnections.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== AUDIT SSH CONNECTIONS  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{AuditSSHConnections.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: Audit Daemons logs
      shell:
        sudo aureport -ts this-month -te now --summary -i | grep failed
      register: AuditDaemonsLogs
    - debug:
        msg: "{{AuditDaemonsLogs.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== AUDIT DAEMON LOGS  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{AuditDaemonsLogs.stdout}}"
        insertafter: OEF
      delegate_to: localhost

    - name: List System services
      shell:
        sudo systemctl list-units --type=service | grep running
      register: ListSystemServices
    - debug:
        msg: "{{ListSystemServices.stdout}}"

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "========== LIST SYSTEM SERVICES  =========="
        insertafter: OEF
      delegate_to: localhost

    - name: append
      lineinfile:
        dest: "{{ destination }}"
        line: "{{ListSystemServices.stdout}}"
        insertafter: OEF
      delegate_to: localhost
