---
- name: LAMP for website
  user: ansibledevops
  hosts: node1
  become: yes
  gather_facts: no 
  tasks:
    - name: install related packages
      yum:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysql
        state: latest
    - name: enable and start HTTP service
      service:
        name: httpd
        enabled: true
        state: started
    - name: enable and start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: get index file
      get_url:
        url: "https://www.middlewareinventory.com/index.php"
        dest: /var/www/html/index.php
        mode: 0644
      check_mode: no
    - name: view webpage
      uri:
        url: http://Node1_Public_IP/index.php
        status_code: 200
      check_mode: no
