---
- name: Docker install and run a container
  hosts: node2
  become: yes
  become_method: sudo
  user: ansibledevops

  tasks:

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
        
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Enable Docker Nightly repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-stable'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      
    - name: Add user ansibledevops to docker group
      user:
        name: ansibledevops
        groups: docker
        append: yes
      become: yes
      
    - name: Check if container is running
      shell: docker ps

    - name: run docker image
      shell: docker run hello-world
